### PR TITLE
Dtraj api

### PR DESCRIPTION
**Pull request by franknoe**
Making all discrete_trajectory functions available as api

### CODE REVIEW

**Comment by franknoe** [comment]
Can someone help me with these Appveyor failures? I think they are windows failures, here the tests run well.

**Comment by marscher** [comment]
It looks like the file used to write the dtraj is still opened in write mode, when it is being tried to read again by the same doctest. This is forbidden in Windows.

**Comment by franknoe** [comment]
I did not change these functions, but just moved the doc strings of the 
former api.py to discrete_trajectories.py and then replaced api.py (that 
was just doing calls to discrete_trajectories.py) by 
discrete_trajectories.py. So I don't see how this could have worked 
before. Could you or Benjamin look into this?

Am 28/07/15 um 12:21 schrieb Martin K. Scherer:

> It looks like the file used to write the dtraj is still opened in 
> write mode, when it is being tried to read again by the same doctest. 
> This is forbidden in Windows.
> 
> —
> Reply to this email directly or view it on GitHub 
> https://github.com/markovmodel/msmtools/pull/39#issuecomment-125543423.

## 

---

Prof. Dr. Frank Noe
Head of Computational Molecular Biology group
Freie Universitaet Berlin

Phone: (+49) (0)30 838 75354
Web:   research.franknoe.de

## Mail:  Arnimallee 6, 14195 Berlin, Germany

**Comment by franknoe** [comment]
Actually the tests _were_ failing before my commit, I just realized that I pushed that branch before committing.

**Comment by marscher** [comment]
please do not refactor code based on open PRs. It was not yet merged,
because appveyor was failing, because we've recently enabled doctesting
on all platforms.

**Comment by franknoe** [comment]
I just realized that I forgot to commit, so the merge would have been 
ineffective without me pushing again.

Am 28/07/15 um 12:35 schrieb Martin K. Scherer:

> please do not refactor code based on open PRs. It was not yet merged,
> because appveyor was failing, because we've recently enabled doctesting
> on all platforms.
> 
> —
> Reply to this email directly or view it on GitHub 
> https://github.com/markovmodel/msmtools/pull/39#issuecomment-125548863.

## 

---

Prof. Dr. Frank Noe
Head of Computational Molecular Biology group
Freie Universitaet Berlin

Phone: (+49) (0)30 838 75354
Web:   research.franknoe.de

## Mail:  Arnimallee 6, 14195 Berlin, Germany

**Pull request merged**
