### PR TITLE
[estimation] Bug fix. i) Sampler with reversible stationary vector ne…

### PR DESCRIPTION
**Pull request by trendelkampschroer**
…eds only check undirected connectivity of count matrix. ii) is_positive checks >=1e-15 instead of >= 1e-8. iii) Use sgamma instead of gengamma to generate Gamma-distributed random variates, possibly avoiding underflow/overflow due to small/large scaling factor beta.

### CODE REVIEW

**Comment by franknoe** [comment]
Thank you very much. Can you please also run the PyEMMA unit tests when using this implementation, to make sure that there are no secondary effects?

**Comment by trendelkampschroer** [comment]
For the latest version of PyEMMA devel I get two errors realted to estimate_hidden_markov_model and timescales_hmsm. 

I also get an import error for the name _get_indices_phi.

But these things don't seem to be related to the sampler, is that correct?

**Comment by marscher** [comment]
Latest version of pyemma needs mdtraj-1.5 and bhmm-0.5.2, please upgrade.

**Comment by trendelkampschroer** [comment]
mdtraj is already version 1.5.1 on my machine, when I do easy_install --user bhmm==0.5.2 I get the following error

Processing bhmm-0.5.2.tar.gz
Writing /tmp/easy_install-nO7Fki/bhmm-0.5.2/setup.cfg
Running bhmm-0.5.2/setup.py -q bdist_egg --dist-dir /tmp/easy_install-nO7Fki/bhmm-0.5.2/egg-dist-tmp-d4D4l2
error: Setup script exited with error: unknown file type '.pyx' (from './bhmm/hidden/impl_c/hidden.pyx')

**Comment by marscher** [comment]
please try pip install bhmm --user

**Comment by marscher** [comment]
upgrade setuptools first: pip install setuptools -U --user; pip install bhmm --user

**Comment by marscher** [comment]
The check if setuptools has a sufficient version seems not to work as expected.

**Comment by trendelkampschroer** [comment]
I've got bhmm-0.5.2. successfully installed, and the HMM-related errors are gone now.

Strangely I still get 

ImportError: cannot import name _get_indices_phi

with a mdtraj version of 1.5.1

**Comment by marscher** [comment]
update your pyemma git/install to at least 2.0.2

**Comment by franknoe** [comment]
Then you don't have PyEMMA 2.0.2.

Am 13/11/15 um 16:30 schrieb Benjamin Trendelkamp-Schroer:

> I've got bhmm-0.5.2. successfully installed, and the HMM-related 
> errors are gone now.
> 
> Strangely I still get
> 
> ImportError: cannot import name _get_indices_phi
> 
> with a mdtraj version of 1.5.1
> 
> —
> Reply to this email directly or view it on GitHub 
> https://github.com/markovmodel/msmtools/pull/62#issuecomment-156464103.

## 

---

Prof. Dr. Frank Noe
Head of Computational Molecular Biology group
Freie Universitaet Berlin

Phone: (+49) (0)30 838 75354
Web:   research.franknoe.de

## Mail:  Arnimallee 6, 14195 Berlin, Germany

**Comment by trendelkampschroer** [comment]
I have PyEMMA latest git devel. I can successfully import pyemma in ipython, the error occurs only if I run nosetests/pyemma. Maybe we can have a look at it together next week.

**Comment by marscher** [comment]
I suppose nose imports pyemma from the wrong location then. If you invoke nose in your git working copy, it should use the right version.

**Comment by trendelkampschroer** [comment]
I have all tests on PyEMMA latest devel running successfully. Can someone please merge this pull-request.

**Comment by franknoe** [comment]
Thank you!

**Pull request merged**
