### PR TITLE
LGPLv3 headers

### PR DESCRIPTION
**Pull request by marscher**

### CODE REVIEW

**Comment by franknoe** [comment]
Ready to release. I suggest version number 1.1 because the main change is a license change.

Changelog:
- License change to LGPL 3.0
- Fixed bug in TPT when requesting a full pathway decomposition of a flux
- More robust calculation of the stationary distribution (falling back to Eigenvector mode if backward iteration doesn't converge)
- New unit tests for reversible transition matrix sampling and TPT.

**Comment by marscher** [comment]
done

**Comment by marscher** [comment]
installable with conda, pip will be available soon

**Comment by franknoe** [comment]
thanks!

Am 31/08/15 um 16:29 schrieb Martin K. Scherer:

> installable with conda, pip will be available soon
> 
> —
> Reply to this email directly or view it on GitHub 
> https://github.com/markovmodel/msmtools/pull/52#issuecomment-136388447.

## 

---

Prof. Dr. Frank Noe
Head of Computational Molecular Biology group
Freie Universitaet Berlin

Phone: (+49) (0)30 838 75354
Web:   research.franknoe.de

## Mail:  Arnimallee 6, 14195 Berlin, Germany

**Pull request merged**
