### PR TITLE
[effective_counts|statistitcal_inefficiency] fix performance due to c…

### LINKED ISSUE #34: estimation.effective_count_matrix is slow
estimation.effective_count_matrix is slow for large data sets, especially with the setting truncate_acf=False. This can probably be sped up by a lot. 
Essentially a lot of damped autocorrelation functions are computed which itself could be sped up. In addition the looping through the acf's from different trajectories is probably unnecessarily slow.

### PR DESCRIPTION
**Pull request by marscher**
…alling setter of csr matrix.

Partially fixes #34

for a dtraj list like this: 100 states, len=10000, number=10 the runtime drops from 55s to 37s.

### CODE REVIEW

**Comment by franknoe** [comment]
Thanks! The new function should give identical results to the old function - have you tested this?

Why aren't the integration tests being started?

**Comment by marscher** [comment]
Yes I've compared Ceff with allclose, btw. all of the stat inefficiency stuff is pretty much untested. Travis has finished, hasn't it?

**Comment by franknoe** [comment]
Am 18/11/15 um 15:49 schrieb Martin K. Scherer:

> Yes I've compared Ceff with allclose, btw. all of the stat 
> inefficiency stuff is pretty much untested.
> 
> Yes, it's hard to come up with a test case.
> 
> Travis has finished, hasn't it?
> 
> Now it has - when I had checked, I didn't even get a test report at all. 
> Weird.
> 
> —
> Reply to this email directly or view it on GitHub 
> https://github.com/markovmodel/msmtools/pull/64#issuecomment-157737503.

## 

---

Prof. Dr. Frank Noe
Head of Computational Molecular Biology group
Freie Universitaet Berlin

Phone: (+49) (0)30 838 75354
Web:   research.franknoe.de

## Mail:  Arnimallee 6, 14195 Berlin, Germany

**Comment by marscher** [comment]
Github introduced a new security setting for third-party application authorization upon organisations, had to disable that.

**Comment by marscher** [comment]
Actually there is a test case which failed on Appveyor for a different shape of si.

**Comment by franknoe** [comment]
Can you please add a test which uses the effective count matrix  from 
the old impl e.g. with the double-well microstate dtraj in our PyEMMA 
data set as a reference result? That way we'll at least be safe to 
algorithmic errors until we have more systematic tests.

Am 18/11/15 um 15:49 schrieb Martin K. Scherer:

> Yes I've compared Ceff with allclose, btw. all of the stat 
> inefficiency stuff is pretty much untested. Travis has finished, 
> hasn't it?
> 
> —
> Reply to this email directly or view it on GitHub 
> https://github.com/markovmodel/msmtools/pull/64#issuecomment-157737503.

## 

---

Prof. Dr. Frank Noe
Head of Computational Molecular Biology group
Freie Universitaet Berlin

Phone: (+49) (0)30 838 75354
Web:   research.franknoe.de

## Mail:  Arnimallee 6, 14195 Berlin, Germany

**Comment by marscher** [comment]
Ok, will add this test for now.

**Comment by marscher** [comment]
This test would require copying the old code over to the unittest (unfiddeling all the dependencies this code has). Moreover the test data set is not yet available in msmtools - do you want me to copy this?

**Comment by marscher** [comment]
I'll add the matrix generated with the old code to the test files.

**Comment by franknoe** [comment]
Yes, that's what I mean

Am 18/11/15 um 16:05 schrieb Martin K. Scherer:

> I'll add the matrix generated with the old code to the test files.
> 
> —
> Reply to this email directly or view it on GitHub 
> https://github.com/markovmodel/msmtools/pull/64#issuecomment-157741674.

## 

---

Prof. Dr. Frank Noe
Head of Computational Molecular Biology group
Freie Universitaet Berlin

Phone: (+49) (0)30 838 75354
Web:   research.franknoe.de

## Mail:  Arnimallee 6, 14195 Berlin, Germany

**Pull request merged**
