### PR TITLE
[MSM/estimators] unify covergence criteria of dense and sparse reversible MSM estimator implementations

### PR DESCRIPTION
**Pull request by fabian-paul**
This addresses issue #71. Dense and sparse implementations now use the same metric to check
for convergence (inf-norm on the relative errors of pi). Both implementations were changed, so expect some changes in the run time of your MSM estimations.
Whether we should use the relative or absolute errors could be discussed. Relative errors on pi are similar to absolute errors on the free energies, so they are sensitive to small probabilities too.
Later we I may add a C implementation of the dense algorithm.

### CODE REVIEW

**Comment by franknoe** [comment]
Looks good to me. @trendelkampschroer pls merge if fine for you

**Comment by fabian-paul** [comment]
What about the return_statdist option that is commented out? Should this be activated?

**Comment by franknoe** [comment]
Where? In `estimate_transition_matrix_reversible` it seems active, and it should be.
Are you talking about the sparse impl?

**Comment by fabian-paul** [comment]
Yes. I see now what is going on. The part that is commented out is actually wrong, so I guess it was deactivated because one didn't get it to work. I'll fix this.

**Comment by trendelkampschroer** [comment]
@fabian-paul: I think you definition of relative error still has a problem: I think x=(1, -1), y=(-1, 1)
will result in division by zero.

**Comment by fabian-paul** [comment]
Thanks Ben, in  msmtools/estimation/dense/transition_matrix.py this should be fixed. I'll do it.
In the C parts I don't think that we have to consider negative elements, because then the estimator would not work anyway.

**Pull request merged**
