### PR TITLE
Readd effective counts

### PR DESCRIPTION
**Pull request by marscher**
This commit was actually added by @franknoe just before @trendelkampschroer and me pulled out the msm subpackage.

Note that the tests will fail until we have the new dtrajs package.

### CODE REVIEW

**Comment by franknoe** [comment]
huh, but this was the first commit in dev_release_1.3, so how could that have been missed? Didn't you extract msmtools from the dev_release_1.3 branch?

**Comment by marscher** [comment]
yes we did this on an up to date dev_release branch. I do not know why this had happened.

**Comment by marscher** [comment]
I've double checked all subpackages of msm, if they are up2date with dev_release branch right now and only this function was missing.

**Comment by franknoe** [comment]
Before deleting something, can we make sure that we don't miss anything 
here? The effective count stuff consists of multiple commits, starting from

https://github.com/markovmodel/PyEMMA/commit/b279765481a1a3715d58e375ad3dbbba04d744c4

to

https://github.com/markovmodel/PyEMMA/commit/ed6779e7d51eba5c33fa8a2f96073375158d0cff

and then another correction happened in

https://github.com/markovmodel/PyEMMA/commit/a8bb502354fbb638c2804288184cc1c6bf0b58f5

Am 14/07/15 um 16:35 schrieb Martin K. Scherer:

> yes we did this on an up to date dev_release branch. I do not know why 
> this had happened.
> 
> —
> Reply to this email directly or view it on GitHub 
> https://github.com/markovmodel/msmtools/pull/20#issuecomment-121256576.

## 

---

Prof. Dr. Frank Noe
Head of Computational Molecular Biology group
Freie Universitaet Berlin

Phone: (+49) (0)30 838 75354
Web:   research.franknoe.de

## Mail:  Arnimallee 6, 14195 Berlin, Germany

**Comment by franknoe** [comment]
note that this function uses pyemma.util.statistics, which is currently 
not included in msmtools

Am 14/07/15 um 16:36 schrieb Martin K. Scherer:

> I've double checked all subpackages of msm, if they are up2date with 
> dev_release branch right now and only this function was missing.
> 
> —
> Reply to this email directly or view it on GitHub 
> https://github.com/markovmodel/msmtools/pull/20#issuecomment-121256780.

## 

---

Prof. Dr. Frank Noe
Head of Computational Molecular Biology group
Freie Universitaet Berlin

Phone: (+49) (0)30 838 75354
Web:   research.franknoe.de

## Mail:  Arnimallee 6, 14195 Berlin, Germany

**Comment by marscher** [comment]
good point. Will the statistics module be contained in the new util git
repo?

**Comment by marscher** [comment]
Am 14.07.2015 um 16:40 schrieb Frank Noe:

> Before deleting something, can we make sure that we don't miss anything
> here?
> I've copied over the latest state from dev_release, so all those fixed
> are contained.

**Comment by franknoe** [comment]
I don't know yet. Copy it into msmtools.util for now.

Am 14/07/15 um 16:43 schrieb Martin K. Scherer:

> good point. Will the statistics module be contained in the new util git
> repo?
> 
> —
> Reply to this email directly or view it on GitHub 
> https://github.com/markovmodel/msmtools/pull/20#issuecomment-121258586.

## 

---

Prof. Dr. Frank Noe
Head of Computational Molecular Biology group
Freie Universitaet Berlin

Phone: (+49) (0)30 838 75354
Web:   research.franknoe.de

## Mail:  Arnimallee 6, 14195 Berlin, Germany

**Comment by franknoe** [comment]
If we create a base module, let's first only put pyemma._base in there 
and things in pyemma.util we're sure that we need to keep in a general 
repo. I have the impression that some pyemma.util things are not really 
used anymore.

Am 14/07/15 um 16:43 schrieb Martin K. Scherer:

> good point. Will the statistics module be contained in the new util git
> repo?
> 
> —
> Reply to this email directly or view it on GitHub 
> https://github.com/markovmodel/msmtools/pull/20#issuecomment-121258586.

## 

---

Prof. Dr. Frank Noe
Head of Computational Molecular Biology group
Freie Universitaet Berlin

Phone: (+49) (0)30 838 75354
Web:   research.franknoe.de

## Mail:  Arnimallee 6, 14195 Berlin, Germany

**Comment by marscher** [comment]
Am 14.07.2015 um 16:47 schrieb Frank Noe:

> If we create a base module, let's first only put pyemma._base in there
> and things in pyemma.util we're sure that we need to keep in a general
> repo. I have the impression that some pyemma.util things are not really
> used anymore.
> Despite deprecated code it also contains code, which we do not want to
> share (eg the logging and config modules).

**Comment by franknoe** [comment]
Am 14/07/15 um 16:48 schrieb Martin K. Scherer:

> Am 14.07.2015 um 16:47 schrieb Frank Noe:
> 
> > If we create a base module, let's first only put pyemma._base in there
> > and things in pyemma.util we're sure that we need to keep in a general
> > repo. I have the impression that some pyemma.util things are not really
> > used anymore.
> > Despite 
> > "except for"
> > deprecated code it also contains code, which we do not want to
> > share (eg the logging and config modules).
> > Logging is actually used in _base.estimator
> 
> —
> Reply to this email directly or view it on GitHub 
> https://github.com/markovmodel/msmtools/pull/20#issuecomment-121262578.

## 

---

Prof. Dr. Frank Noe
Head of Computational Molecular Biology group
Freie Universitaet Berlin

Phone: (+49) (0)30 838 75354
Web:   research.franknoe.de

## Mail:  Arnimallee 6, 14195 Berlin, Germany

**Comment by marscher** [comment]
The logging initialization also depends on the pyemma config file. I do not see how to easily untangle this.

**Comment by marscher** [comment]
but I'm getting off topic right now. I will copy over the statistics module right now.

**Pull request merged**
