### PR TITLE
made reversible eigenvalue computation more robust and introduced fal…

### PR DESCRIPTION
**Pull request by franknoe**
…lback option

### CODE REVIEW

**Comment by franknoe** [comment]
Very weird. These test failures do not occur on my Mac. I also don't think that the changes introduced here are the source of error, but rather reveal a problem that has been there before. @trendelkampschroer , could you have a look?

**Comment by marscher** [comment]
Interestingly the Windows tests passed also. So it has to be related to Linux somehow (library stuff ...). I've restarted the latest devel state travis build and it also fails (it actually crashed the docker container, which is very unlikely to happen - so something is seriously broken).

Scipy just got upgraded to 0.17 and uses a MKL (which is an Intel math/algebra lib), which very likely provides the eigensolver we are using. If that's the case, this is an upstream problem (in conda), which we will have to wait until it is fixed.

I think @cwehmeyer and @jhprinz told me, that they were also experiencing problems with scipy in recent upgrades.

**Comment by franknoe** [comment]
oh no.

Am 11/02/16 um 03:03 schrieb Martin K. Scherer:

> Interestingly the Windows tests passed also. So it has to be related 
> to Linux somehow (library stuff ...). I've restarted the latest devel 
> state travis build and it also fails (it actually crashed the docker 
> container, which is very unlikely to happen - so something is 
> seriously broken).
> 
> Scipy just got upgraded to 0.17 and uses a MKL (which is an Intel 
> math/algebra lib), which very likely provides the eigensolver we are 
> using. If that's the case, this is an upstream problem (in conda), 
> which we will have to wait until it is fixed.
> 
> I think @cwehmeyer https://github.com/cwehmeyer and @jhprinz 
> https://github.com/jhprinz told me, that they were also experiencing 
> problems with scipy in recent upgrades.
> 
> —
> Reply to this email directly or view it on GitHub 
> https://github.com/markovmodel/msmtools/pull/79#issuecomment-182671973.

## 

---

Prof. Dr. Frank Noe
Head of Computational Molecular Biology group
Freie Universitaet Berlin

Phone: (+49) (0)30 838 75354
Web:   research.franknoe.de

## Mail:  Arnimallee 6, 14195 Berlin, Germany

**Comment by marscher** [comment]
I guess if first upgrade to NumPy 1.10.4, you will also experience this
bug. So downgrading to version 1.10.2 (which does not have this MKL
dependency yet) could help...

**Comment by franknoe** [comment]
It's likely that someone else has run into this, so let's first find out 
if there is some activity to fix it.

Constraining numpy + scipy versions in our install dependencies could 
cause problems, whereas PyEMMA will most likely not be affected from a 
problem in the sparse eigensolver.

Am 11/02/16 um 03:10 schrieb Martin K. Scherer:

> I guess if first upgrade to NumPy 1.10.4, you will also experience this
> bug. So downgrading to version 1.10.2 (which does not have this MKL
> dependency yet) could help...
> 
> —
> Reply to this email directly or view it on GitHub 
> https://github.com/markovmodel/msmtools/pull/79#issuecomment-182673064.

## 

---

Prof. Dr. Frank Noe
Head of Computational Molecular Biology group
Freie Universitaet Berlin

Phone: (+49) (0)30 838 75354
Web:   research.franknoe.de

## Mail:  Arnimallee 6, 14195 Berlin, Germany

**Comment by marscher** [comment]
I think avoiding MKL in the mean time should help. I'm currently writing
an issue in the Anaconda repo.

**Comment by marscher** [comment]
upstream issue ContinuumIO/anaconda-issues/issues/658

**Comment by marscher** [comment]
I think you should merge this. Luckily we have more than one testing platform and the travis failures are clearly caused by the MKL bug.

**Comment by rmcgibbo** [comment]
@marscher if you can make a simple self-contained test case that just depends on numpy/scipy, I'd be interested to look at it.

**Comment by marscher** [comment]
Will do. Hold on...

**Comment by marscher** [comment]
https://gist.github.com/marscher/bb0d40d4012a8696aa71

**Comment by rmcgibbo** [comment]
... lol. i figured it would be possible to get a minimal test case, just like with `X=..., assert scipy.linalg.eigh(X) = ...`

**Comment by marscher** [comment]
:) I'd just red "does only depend on numpy/scipy"  -- sorry

**Pull request merged**
