### PR TITLE
please ignore this PR

### PR DESCRIPTION
**Pull request by fabian-paul**
triggering travis etc to check practical support of C restrict pointers

### CODE REVIEW

**Comment by marscher** [comment]
Just push a new branch to this repo, you actually do not need a PR for that :+1:

**Comment by marscher** [comment]
Ah you got a new account, do you think the compiler will do clever tricks on this restricted pointers?

**Comment by marscher** [comment]
Guess what, restrict is a c99 feature?

**Comment by fabian-paul** [comment]
Well I can't push to msmtools, so this is the only option to use the cloud services without registering.
gcc had it before as "**restrict**" so I think I can make it work.

**Pull request closed without merging**
