### PR TITLE
Feature sampling

### PR DESCRIPTION
**Pull request by trendelkampschroer**
Implementations of reversible sampling algorithms

### CODE REVIEW

**Comment by franknoe** [comment]
Please remove unused test functions. I think these are in sample_rev.c and *.h:
- _update_sparse_speedtest
- _test_gamma
- _test_norm
- _test_pre
- _test_else1
- _test_else2
- _test_update_step

Initialization of reversible sampler: If I see it correctly you removed the MLE initialization and replaced it by:

```
            A = C + C.T
            V0 = A/A.sum()
```

which is OK for equilibrium data but a bad starting point for short trajectories with out-of-equilibrium starting points. Why?
The MLE calculation could be slow, but what about at least doing it for a few steps?

**Comment by trendelkampschroer** [comment]
This was the starting point originally suggested by Hao, I kept it since then, but I can change it to MLE. 

I will remove the unused test functions and submit a new pull request.

**Comment by trendelkampschroer** [comment]
Done

**Comment by franknoe** [comment]
Thanks a lot for a great feature Benjamin. Merging and trying it out...

**Comment by franknoe** [comment]
This breaks pyEMMA functionality because of a keyword name change. Not a big deal to fix, but in the future I think we need to run pyEMMA tests after changing msmtools.

There are also a few minor things that can be automatically found, such as using `statidist` instead of `statdist` in the nonreversible sampler (probably not tested). Please use a development environment that checks the code. 

I'll go ahead and fix these things.

**Comment by marscher** [comment]
Am 16.07.2015 um 17:47 schrieb Frank Noe:

**Comment by franknoe** [comment]
Am 16/07/15 um 17:51 schrieb Martin K. Scherer:

> Am 16.07.2015 um 17:47 schrieb Frank Noe:
> 
> > This breaks pyEMMA functionality because of a keyword name change. Not a
> > big deal to fix, but in the future I think we need to run pyEMMA tests
> > after changing msmtools.
> > Actually the pyemma travis job uses the git version of msmtools to
> > ensure we always test against the latest development.
> > Fine, but what I meant is that when making changes to msmtools and 
> > pushing a PR one should run the pyEMMA tests to see if one has created a 
> > problem there - because the msmtools travis job doesn't do that.
> > Clearly we can't do that for all packages that will be using msmtools in 
> > the future, but I think it's not to much to ask to do it for pyEMMA 
> > which is the main user. In the present case the problem was due to an 
> > API change, i.e. one-sided change of contract.
> > 
> > There are also a few minor things that can be automatically found, such
> > as using |statidist| instead of |statdist| in the nonreversible sampler
> > (probably not tested). Please use a development environment that checks
> > the code.
> > 
> > I'll go ahead and fix these things.
> > 
> > —
> > Reply to this email directly or view it on GitHub
> > 
> > https://github.com/markovmodel/msmtools/pull/28#issuecomment-121998517.
> 
> —
> Reply to this email directly or view it on GitHub 
> https://github.com/markovmodel/msmtools/pull/28#issuecomment-121999691.

## 

---

Prof. Dr. Frank Noe
Head of Computational Molecular Biology group
Freie Universitaet Berlin

Phone: (+49) (0)30 838 75354
Web:   research.franknoe.de

## Mail:  Arnimallee 6, 14195 Berlin, Germany

**Pull request merged**
