### PR TITLE
added rate matrix estimation

### PR DESCRIPTION
**Pull request by fabian-paul**

### CODE REVIEW

**Comment by franknoe** [comment]
Following the naming logic of `estimation.transition_matrix` we should maybe just call this one `rate_matrix`.

I think it would be useful if @rmcgibbon takes a look to see if he has any code that would be useful to be added. I think Robert and Fabian also use slightly different formulation of the function to be minimized. Do we know anything about differences in efficiency? Could we just plot some convergence of the two approaches for a few test-C-matrices?

**Comment by franknoe** [comment]
And _thanks_ this is a substantial contribution!

**Comment by rmcgibbo** [comment]
My implementation is pretty completely described in my JCP paper. It's all done in very efficient low-level cython -- I read all the generated C code -- with explicit BLAS / LAPACK calls, avoidance of unnecessary transpositions and reuse of matrix buffers to avoid unnecessary mallocs. The paper shows some benchmarks as a function of the number of states.

**Comment by rmcgibbo** [comment]
Also, from a software engineering perspective, I noticed this PR includes ~10K lines of copy-pasted code from scipy, which is somewhat of a concern to me.

**Comment by rmcgibbo** [comment]
The low-level code is all here: https://github.com/msmbuilder/msmbuilder/blob/master/msmbuilder/msm/_ratematrix.pyx. It should be relatively well documented inline.

I haven't read this PR completely, but one key difference in the algorithm, I believe, is that the code in this PR seems to use a single fixed stationary eigenvector, whereas the version above treats the (log of) the stationary eigenvector as a free parameter too, in addition to the symmetric rate constants.

**Comment by franknoe** [comment]
These are multiple issues, but let me try to address some of them:
1. Stationary distribution: It appears Fabian is computing the stationary distribution from the transition matrix or pseudogenerator and then using it in the maximization of the KL-likelihood of the rate matrix. Although P = exp(tau K) and K will have the same stationary distribution, it is not clear to me whether a MLE of P and a MLE of K will give the same estimate for the stationary distribution. Do we have the property that exp(tau K) from our estimated K is identical to an independent estimate of P? So are we actually really finding the maximum of the KL-likelihood when pi is not set by the user? A simple test would be to compare the MLE results and likelihoods of Fabian's and Roberts code for a few given count matrices. If that's not equal we're solving different problems here.
2. There are two efficiency aspects here: One is the efficient code implementation of an iteration described by Robert, and that's an important issue. What I meant is since you are apparently using somewhat different mathematical formulations to write the likelihood in terms of your search variables and its derivatives, do these different formulations lead to different convergence behavior in the BFGS algorithm? Residual error or likelihood vs number of iterations. I guess 1. needs to be addressed before 2, otherwise we are comparing pines and pineapples.
3. Scipy copy-paste: Fabian should comment on that. If I understand the comments correctly this is temporarily necessary because Fabian made modifications to the scipy code that will only be available in the next scipy release. But do we really need all 10K lines?
4. Robert: thanks for these pointers. I don't think we can copy code from msmbuilder (even if the license would permit), but you could contribute it to msmtools of course, once 1/2 is understood and we know what combination of codes makes sense.

Since 1/2 are not completely trivial, perhaps you could start a new issue on these.

**Comment by rmcgibbo** [comment]
- The matrix exponential isn't bijective, so I would be very surprised if the MLE of the continuous-time model and the discrete-time model were identical, given the same count matrix. I expect they're close, but not identical. Only a subset of stochastic matrices are embeddable; if the MLE P-matrix happens to be embeddable, it might have the identical stationary distribution to the MLE rate matrix, but that's extremely rare.
- Other than the stationary distribution difference, I believe the rest of the parameterization of the independent variables is identical between the two codebases.
- I'm happy to contribute whatever code to this package.

**Comment by franknoe** [comment]
OK, Fabian: can you have a look at these points whenever time permits. 
Thanks Robert!

Am 11/09/15 um 20:26 schrieb Robert T. McGibbon:

> - The matrix exponential isn't bijective, so I would be very
>   surprised if the MLE of the continuous-time model and the
>   discrete-time model were identical, given the same count matrix. I
>   expect they're close, but not identical. O a subset of stochastic
>   matrices are embeddable; if the MLE P-matrix happens to be
>   embeddable, it might have the identical stationary distribution to
>   the MLE rate matrix, but that's extremely rare.
> - Other than the stationary distribution difference, I believe the
>   rest of the parameterization of the independent variables is
>   identical between the two codebases.
> - I'm happy to contribute whatever code to this package.
> 
> —
> Reply to this email directly or view it on GitHub 
> https://github.com/markovmodel/msmtools/pull/57#issuecomment-139620004.

## 

---

Prof. Dr. Frank Noe
Head of Computational Molecular Biology group
Freie Universitaet Berlin

Phone: (+49) (0)30 838 75354
Web:   research.franknoe.de

## Mail:  Arnimallee 6, 14195 Berlin, Germany

**Comment by fabian-paul** [comment]
Here is a short answer, I will answer at length next week.
issue 1: I don't know, guess we have to do some pen and paper work.
issue 2: Not sure either. How do parametrizations affect the minimization? There are arbitrarily many choices of the parametrization. How do we decide which is best? Has anyone any literature references about this subject?
issue 3: the 10k lines are a temporary fix and can be removed once scipy 0.17 is out (here is the correct fix: scipy/scipy#5105). Personally, I could wait for scipy 0.17 and leave the C code out of msmtools.
issue 4:  I'm really ok with any implementation be it Robert's or mine.

**Comment by franknoe** [comment]
Am 11/09/15 um 22:08 schrieb fabian-paul:

> Here is a short answer, I will answer at length next week.
> issue 1: I don't know, guess we have to do some pen and paper work.
> 
> Falsifying would be easy, but running an example. My intuition is like 
> Robert's, these estimators are probably
> 
> issue 2: Not sure either. How do parametrizations affect the 
> minimization? There are arbitrarily many choices of the 
> parametrization. How do we decide which is best? Has anyone any 
> literature references about this subject?
> 
> No idea, but Ben and Hao are pretty good references for that. I think 
> for now it would be sufficient to run a few optimizations on toy 
> problems and see if there is any clear tendency. But it requires to 
> clear issue 1 first, because constraining to a given pi-vector will 
> certainly affect the convergence rate.
> 
> issue 3: the 10k lines are a temporary fix and can be removed once 
> scipy 0.17 is out (here is the correct fix: scipy/scipy#5105 
> https://github.com/scipy/scipy/pull/5105). Personally, I could wait 
> for scipy 0.17 and leave the C code out of msmtools.
> 
> Do we have a release date for that? If there are no license issues, I 
> think it's ok to have these lines added temporarily and removed later.
> 
> issue 4: I'm really ok with any implementation be it Robert's or mine.
> 
> OK, let's address 1+2 and then decide what the best of both is.
> 
> —
> Reply to this email directly or view it on GitHub 
> https://github.com/markovmodel/msmtools/pull/57#issuecomment-139649699.

## 

---

Prof. Dr. Frank Noe
Head of Computational Molecular Biology group
Freie Universitaet Berlin

Phone: (+49) (0)30 838 75354
Web:   research.franknoe.de

## Mail:  Arnimallee 6, 14195 Berlin, Germany

**Comment by franknoe** [comment]
Just a minor thing, since we have `estimation.transition_matrix` for the transition matrix estimator, can you change the name into `estimation.rate_matrix` for consistency? I'll merge right after.

**Comment by franknoe** [comment]
the name estimate_rate_matrix is still used in a doctest, that fails now.

**Comment by fabian-paul** [comment]
Thanks!

**Comment by franknoe** [comment]
Läuft. Danke!!

**Pull request merged**
